# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |

   curl -u "42a1d8855cf2431f0020a9b602eb63be:kHcvihIKP05hiexM0ZXunUUD2MJqbcSDEaiZXgOefnA=" -X POST http://9d0fa76f.ngrok.io/api/1.0/scans/CreateFromPluginScanRequest -H "Content-Type: application/json" -d "{ WebsiteId: '203487f9-4cff-4a44-02d0-a9bc01beffb6', 'ProfileId': '9240fdbf-d12b-44c5-0358-a9bc01bfe36e', 'ScanType': 'Incremental', 'VcsCommitInfoModel': { 'CiBuildConfigurationName' : '$BUILD_DEFINITIONNAME', 'CiBuildHasChange': '$BUILD_SOURCEVERSION', 'CiBuildId': '$BUILD_BUILDID', 'CiBuildUrl': '$RELEASE_RELEASEWEBURL', 'Committer': '$BUILD_REQUESTEDFOREMAIL', 'IntegrationSystem': 'AzureDevOps', 'VcsName': '$BUILD_REPOSITORY_PROVIDER', 'VcsVersion': '$BUILD_SOURCEVERSION' }}"